# Development

services:
  intermine_builder:
    build:
      context: ./intermine_builder
      dockerfile: ./intermine_builder.Dockerfile
      args:
        MINE_NAME: ${MINE_NAME}
    volumes:
      - ./data/data-store:/home/intermine/data/data-store:ro
      - /home/intermine/.gradle
    depends_on: 
      postgres:
        condition: service_healthy
      solr:
        condition: service_started
      tomcat:
        condition: service_started

  postgres:
    image: docker.io/library/postgres:17-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --auth=peer --encoding=SQL_ASCII --lc-collate=C --lc-ctype=C
    user: postgres
    command: ["-c", "config_file=/opt/postgresql.conf",
              "-c", "checkpoint_timeout=60min",
              "-c", "fsync=off",
              "-c", "max_wal_senders=0",
              "-c", "max_wal_size=4GB",
              "-c", "wal_compression=zstd",
              "-c", "wal_level=minimal"]
    healthcheck:
      test: "pg_isready || exit 1"
    volumes:
      - ./postgres/init_postgresql.sql:/docker-entrypoint-initdb.d/init_postgresql.sql:ro
      - ./postgres/postgresql.conf:/opt/postgresql.conf:ro
      - /var/lib/postgresql/data

  solr:
    build:
      context: ./solr
      dockerfile: ./solr.Dockerfile
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx2g -Xms1s"}
      - MINE_NAME=${MINE_NAME}
    volumes:
      - /var/solr

  tomcat:
    build:
      context: ./tomcat
      dockerfile: ./tomcat.Dockerfile
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx1g -Xms500m"}
    ports:
      - ${TOMCAT_HOST_PORT:-9999}:${TOMCAT_PORT:-8080}
