# https://github.com/intermine/im-docs/blob/78c33ce8fcfdbb336c995daf869bb1b742fccb95/docs/web-services/intermine-properties.md?plain=1#L9

db.production.datasource.serverName=PGHOST
db.production.datasource.port=PGPORT
db.production.datasource.databaseName=mine
db.production.datasource.user=PGUSER
db.production.datasource.password=PGPASSWORD

db.common-tgt-items.datasource.serverName=PGHOST
db.common-tgt-items.datasource.port=PGPORT
db.common-tgt-items.datasource.databaseName=items-mine
db.common-tgt-items.datasource.user=PGUSER
db.common-tgt-items.datasource.password=PGPASSWORD

db.userprofile-production.datasource.serverName=PGHOST
db.userprofile-production.datasource.port=PGPORT
db.userprofile-production.datasource.databaseName=userprofile-mine
db.userprofile-production.datasource.user=PGUSER
db.userprofile-production.datasource.password=PGPASSWORD

webapp.deploy.url=http://TOMCAT_HOST_PORT
webapp.path=MINE_NAME
webapp.manager=TOMCAT_USER
webapp.password=TOMCAT_PWD

superuser.account=superuser
superuser.initialPassword=superuser
